### ISSUE TITLE
Use the `atom-text-editor` tag instead of the `editor` class.

### ISSUE THREAD

**Issue by jacobbednarz** [benogle/line-jumper#1]
In keymaps/line-jumper.cson: Use the `atom-text-editor` tag instead of the `editor` class.

**Comment by benogle** [comment]
Fixed in latest

**Comment by kankaristo** [comment]
This isn't fixed yet?

There was a new release (0.14), but it didn't change `keymap.cson` (which is where this deprecation is).

**Comment by benogle** [comment]
Sorry about that. It's out in 0.14.1
